services:
  - type: web
    name: CyclingApp
    env: ruby
    region: singapore
    plan: free
    buildCommand: "bundle install && bundle exec rake db:migrate && bundle exec rails db:seed"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cycling-db
          property: connectionString
